### ISSUE TITLE
Show links to source docs when displaying search results

### ISSUE THREAD

**Issue by zeke** [replicate/replicate-retriever#2]
![Screenshot 2023-11-16 at 09 45 57](https://github.com/replicate/replicate-retriever/assets/2289/76de6add-e58d-4fce-b1c0-94177c88af88)

**Comment by Pwntus** [comment]
Fixed in 142ddff418e5a66be6aa9933d807b0ee48b5dda5

<img width="766" alt="Screenshot 2023-11-20 at 18 24 34" src="https://github.com/replicate/replicate-retriever/assets/854759/034d8c4e-8d53-4aa5-a08b-277e216defbc">

**Comment by zeke** [comment]
Nice!
